global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "api-service"
    static_configs:
      - targets: ["api-service:3005"]

  - job_name: "cadvisor"
    static_configs:
      - targets: ["cadvisor:8080"]

  - job_name: "node-exporter"
    static_configs:
      - targets: ["node-exporter:9100"]
